In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('country_profile_variables.csv')

In [3]:
df.tail()

,country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
224,Wallis and Futuna Islands,Polynesia,142,12,84.1,93.4,-99,-99,-99.0,-99,...,9.0,89,41.6,~0.0/1.6,-99,26,-99,-99,-99,-99
225,Western Sahara,NorthernAfrica,266000,553,2.1,110.1,-99,-99,-99.0,-99,...,-99,49,2.7,-99,-99,-99,-99,-99,-99,-99
226,Yemen,WesternAsia,527968,28250,53.5,102.1,29688,-28.1,1106.4,14.7,...,25.1,298,1.0,22.7/0.9,668,12,72.0/46.5,92.5/34.1,2.99,-99
227,Zambia,EasternAfrica,752612,17094,23.0,98.5,21255,2.9,1311.1,8.2,...,21.0,88,65.6,4.5/0.3,374,26,85.6/51.3,55.6/35.7,3.96,-99
228,Zimbabwe,EasternAfrica,390757,16530,42.7,95.0,13893,1.1,890.4,13.0,...,16.4,89,37.2,12.0/0.8,482,30,97.0/67.3,49.3/30.8,6.00,-99

In [4]:
df.shape

(229, 50)

In [5]:
df['Region'].unique()

array(['SouthernAsia', 'SouthernEurope', 'NorthernAfrica', 'Polynesia',
       'MiddleAfrica', 'Caribbean', 'SouthAmerica', 'WesternAsia',
       'Oceania', 'WesternEurope', 'EasternEurope', 'CentralAmerica',
       'WesternAfrica', 'NorthernAmerica', 'SouthernAfrica',
       'South-easternAsia', 'EasternAfrica', 'NorthernEurope',
       'EasternAsia', 'Melanesia', 'Micronesia', 'CentralAsia'],
      dtype=object)

In [6]:
df["Region"].unique().shape

(22,)

In [7]:
df.isnull().sum()

country                                                       0
Region                                                        0
Surface area (km2)                                            0
Population in thousands (2017)                                0
Population density (per km2, 2017)                            0
Sex ratio (m per 100 f, 2017)                                 0
GDP: Gross domestic product (million current US$)             0
GDP growth rate (annual %, const. 2005 prices)                0
GDP per capita (current US$)                                  0
Economy: Agriculture (% of GVA)                               0
Economy: Industry (% of GVA)                                  0
Economy: Services and other activity (% of GVA)               0
Employment: Agriculture (% of employed)                       0
Employment: Industry (% of employed)                          0
Employment: Services (% of employed)                          0
Unemployment (% of labour force)                              0
Labour force participation (female/male pop. %)               0
Agricultural production index (2004-2006=100)                 0
Food production index (2004-2006=100)                         0
International trade: Exports (million US$)                    0
International trade: Imports (million US$)                    0
International trade: Balance (million US$)                    0
Balance of payments, current account (million US$)            0
Population growth rate (average annual %)                     0
Urban population (% of total population)                      0
Urban population growth rate (average annual %)               0
Fertility rate, total (live births per woman)                 0
Life expectancy at birth (females/males, years)               0
Population age distribution (0-14 / 60+ years, %)             0
International migrant stock (000/% of total pop.)             0
Refugees and others of concern to UNHCR (in thousands)        0
Infant mortality rate (per 1000 live births                   0
Health: Total expenditure (% of GDP)                          0
Health: Physicians (per 1000 pop.)                            0
Education: Government expenditure (% of GDP)                  0
Education: Primary gross enrol. ratio (f/m per 100 pop.)      0
Education: Secondary gross enrol. ratio (f/m per 100 pop.)    0
Education: Tertiary gross enrol. ratio (f/m per 100 pop.)     0
Seats held by women in national parliaments %                 0
Mobile-cellular subscriptions (per 100 inhabitants)           0
Mobile-cellular subscriptions (per 100 inhabitants).1         0
Individuals using the Internet (per 100 inhabitants)          0
Threatened species (number)                                   0
Forested area (% of land area)                                0
CO2 emission estimates (million tons/tons per capita)         0
Energy production, primary (Petajoules)                       0
Energy supply per capita (Gigajoules)                         0
Pop. using improved drinking water (urban/rural, %)           0
Pop. using improved sanitation facilities (urban/rural, %)    0
Net Official Development Assist. received (% of GNI)          0
dtype: int64

In [8]:
df.duplicated().sum()

0

In [14]:
df.dtypes

country                                                        object
Region                                                         object
Surface area (km2)                                             object
Population in thousands (2017)                                  int64
Population density (per km2, 2017)                            float64
Sex ratio (m per 100 f, 2017)                                 float64
GDP: Gross domestic product (million current US$)               int64
GDP growth rate (annual %, const. 2005 prices)                 object
GDP per capita (current US$)                                  float64
Economy: Agriculture (% of GVA)                                object
Economy: Industry (% of GVA)                                  float64
Economy: Services and other activity (% of GVA)               float64
Employment: Agriculture (% of employed)                        object
Employment: Industry (% of employed)                           object
Employment: Services (% of employed)                           object
Unemployment (% of labour force)                               object
Labour force participation (female/male pop. %)                object
Agricultural production index (2004-2006=100)                   int64
Food production index (2004-2006=100)                           int64
International trade: Exports (million US$)                     object
International trade: Imports (million US$)                     object
International trade: Balance (million US$)                     object
Balance of payments, current account (million US$)             object
Population growth rate (average annual %)                      object
Urban population (% of total population)                      float64
Urban population growth rate (average annual %)                object
Fertility rate, total (live births per woman)                  object
Life expectancy at birth (females/males, years)                object
Population age distribution (0-14 / 60+ years, %)              object
International migrant stock (000/% of total pop.)              object
Refugees and others of concern to UNHCR (in thousands)         object
Infant mortality rate (per 1000 live births                    object
Health: Total expenditure (% of GDP)                          float64
Health: Physicians (per 1000 pop.)                             object
Education: Government expenditure (% of GDP)                   object
Education: Primary gross enrol. ratio (f/m per 100 pop.)       object
Education: Secondary gross enrol. ratio (f/m per 100 pop.)     object
Education: Tertiary gross enrol. ratio (f/m per 100 pop.)      object
Seats held by women in national parliaments %                 float64
Mobile-cellular subscriptions (per 100 inhabitants)            object
Mobile-cellular subscriptions (per 100 inhabitants).1          object
Individuals using the Internet (per 100 inhabitants)            int64
Threatened species (number)                                    object
Forested area (% of land area)                                 object
CO2 emission estimates (million tons/tons per capita)           int64
Energy production, primary (Petajoules)                         int64
Energy supply per capita (Gigajoules)                          object
Pop. using improved drinking water (urban/rural, %)            object
Pop. using improved sanitation facilities (urban/rural, %)     object
Net Official Development Assist. received (% of GNI)            int64
dtype: object

In [20]:
df["Surface area (km2)"]=pd.to_numeric(df["Surface area (km2)"],errors='coerce')

In [21]:
df.dtypes

country                                                        object
Region                                                         object
Surface area (km2)                                            float64
Population in thousands (2017)                                  int64
Population density (per km2, 2017)                            float64
Sex ratio (m per 100 f, 2017)                                 float64
GDP: Gross domestic product (million current US$)               int64
GDP growth rate (annual %, const. 2005 prices)                 object
GDP per capita (current US$)                                  float64
Economy: Agriculture (% of GVA)                                object
Economy: Industry (% of GVA)                                  float64
Economy: Services and other activity (% of GVA)               float64
Employment: Agriculture (% of employed)                        object
Employment: Industry (% of employed)                           object
Employment: Services (% of employed)                           object
Unemployment (% of labour force)                               object
Labour force participation (female/male pop. %)                object
Agricultural production index (2004-2006=100)                   int64
Food production index (2004-2006=100)                           int64
International trade: Exports (million US$)                     object
International trade: Imports (million US$)                     object
International trade: Balance (million US$)                     object
Balance of payments, current account (million US$)             object
Population growth rate (average annual %)                      object
Urban population (% of total population)                      float64
Urban population growth rate (average annual %)                object
Fertility rate, total (live births per woman)                  object
Life expectancy at birth (females/males, years)                object
Population age distribution (0-14 / 60+ years, %)              object
International migrant stock (000/% of total pop.)              object
Refugees and others of concern to UNHCR (in thousands)         object
Infant mortality rate (per 1000 live births                    object
Health: Total expenditure (% of GDP)                          float64
Health: Physicians (per 1000 pop.)                             object
Education: Government expenditure (% of GDP)                   object
Education: Primary gross enrol. ratio (f/m per 100 pop.)       object
Education: Secondary gross enrol. ratio (f/m per 100 pop.)     object
Education: Tertiary gross enrol. ratio (f/m per 100 pop.)      object
Seats held by women in national parliaments %                 float64
Mobile-cellular subscriptions (per 100 inhabitants)            object
Mobile-cellular subscriptions (per 100 inhabitants).1          object
Individuals using the Internet (per 100 inhabitants)            int64
Threatened species (number)                                    object
Forested area (% of land area)                                 object
CO2 emission estimates (million tons/tons per capita)           int64
Energy production, primary (Petajoules)                         int64
Energy supply per capita (Gigajoules)                          object
Pop. using improved drinking water (urban/rural, %)            object
Pop. using improved sanitation facilities (urban/rural, %)     object
Net Official Development Assist. received (% of GNI)            int64
dtype: object

In [27]:
sa=df.groupby("Region").sum()[["Surface area (km2)"]].sort_values("Surface area (km2)",ascending=False).reset_index()

In [28]:
sa

               Region  Surface area (km2)
0     NorthernAmerica          21984568.0
1       EasternEurope          18826191.0
2        SouthAmerica          17801955.0
3         EasternAsia          11764004.0
4             Oceania           7960167.0
5       EasternAfrica           7029667.0
6        SouthernAsia           6764027.0
7        MiddleAfrica           6612876.0
8      NorthernAfrica           5936000.0
9       WesternAfrica           5822711.0
10        WesternAsia           4884928.0
11  South-easternAsia           4501156.0
12        CentralAsia           4004520.0
13     SouthernAfrica           2674871.0
14     CentralAmerica           2486556.0
15     NorthernEurope           1798652.0
16     SouthernEurope           1317898.0
17      WesternEurope           1108856.0
18          Melanesia            540772.0
19          Caribbean            233239.0
20          Polynesia              8464.0
21         Micronesia              3095.0

In [32]:
country=df["country"].unique().tolist()

In [33]:
country.sort()

In [34]:
country

['Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia (Plurinational State of)',
 'Bonaire, Sint Eustatius and Saba',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Channel Islands',
 'Chile',
 'China',
 'China, Hong Kong SAR',
 'China, Macao SAR',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 "Democratic People's Republic of Korea",
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Falkland Islands (Malvinas)',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'French Polynesia',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Holy See',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran (Islamic Republic of)',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Kyrgyzstan',
 "Lao People's Democratic Republic",
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Micronesia (Federated States of)',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'Northern Mariana Islands',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Republic of Korea',
 'Republic of Moldova',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten (Dutch part)',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'State of Palestine',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Tajikistan',
 'Thailand',
 'The former Yugoslav Republic of Macedonia',
 'Timor-Leste',
 'Togo',
 'Tokelau',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United Republic of Tanzania',
 'United States Virgin Islands',
 'United States of America',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela (Bolivarian Republic of)',
 'Viet Nam',
 'Wallis and Futuna Islands',
 'Western Sahara',
 'Yemen',
 'Zambia',
 'Zimbabwe']